import { useEffect, useState } from "react";
import { hostFetch } from "../host/tauri-http.js";
import "./client.css";

type Project = { readonly projectId: string; readonly name: string; readonly rootFolder: string };
type Conversation = { readonly id: string; readonly title: string; readonly workspaceId: string; readonly revision: number; readonly messages?: readonly { readonly role: string; readonly text: string }[] };
async function request<T>(path: string, init: RequestInit = {}): Promise<T> { const response = await hostFetch(path, init); const body = await response.json() as T & { error?: { message?: string } }; if (!response.ok) throw new Error(body.error?.message ?? "Platform request failed."); return body; }
export function PlatformPage(props: { readonly active: boolean; readonly model: string }) {
  const [available, setAvailable] = useState<boolean>(); const [projects, setProjects] = useState<readonly Project[]>([]); const [projectId, setProjectId] = useState(""); const [conversations, setConversations] = useState<readonly Conversation[]>([]); const [conversation, setConversation] = useState<Conversation>(); const [title, setTitle] = useState(""); const [draft, setDraft] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { if (!props.active) return; void request<{ available: boolean }>("/v3/info").then((info) => setAvailable(info.available)).catch(() => setAvailable(false)); void request<{ projects: readonly Project[] }>("/v1/projects").then((result) => setProjects(result.projects)).catch(() => undefined); }, [props.active]);
  function selectProject(next: string) { setProjectId(next); setConversation(undefined); void request<{ conversations: readonly Conversation[] }>(`/v3/projects/${encodeURIComponent(next)}/conversations`).then((result) => setConversations(result.conversations)).catch((reason) => setMessage(reason instanceof Error ? reason.message : "Could not load conversations.")); }
  async function createConversation(): Promise<void> { if (!projectId || !title.trim()) return; setBusy(true); try { const result = await request<{ conversation: Conversation }>(`/v3/projects/${encodeURIComponent(projectId)}/conversations`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ title: title.trim() }) }); setTitle(""); setConversation(result.conversation); selectProject(projectId); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Could not create conversation."); } finally { setBusy(false); } }
  async function startRun(): Promise<void> { if (!conversation || !draft.trim() || !props.model.trim()) return; setBusy(true); try { const result = await request<{ run: { id: string; status: string } }>(`/v3/conversations/${encodeURIComponent(conversation.id)}/runs`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ commandId: crypto.randomUUID(), expectedRevision: conversation.revision, model: props.model, text: draft.trim() }) }); setDraft(""); setMessage(`Run ${result.run.id}: ${result.run.status}`); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Could not start run."); } finally { setBusy(false); } }
  return <section className="a008-platform" aria-label="Platform"><header><p>PLATFORM V3</p><h1>Platform</h1></header>{available === false ? <p className="a008-note">Platform V3 is unavailable. No run was started.</p> : null}{available ? <div className="a008-platform-grid"><label>Project<select aria-label="Platform project" value={projectId} onChange={(event) => selectProject(event.currentTarget.value)}><option value="">Select a project</option>{projects.map((project) => <option key={project.projectId} value={project.projectId}>{project.name}</option>)}</select></label><label>Conversation title<input aria-label="Conversation title" value={title} onChange={(event) => setTitle(event.currentTarget.value)} /></label><button type="button" disabled={busy || !projectId || !title.trim()} onClick={() => void createConversation()}>Create conversation</button><ul className="a008-project-list">{conversations.map((item) => <li key={item.id}><button type="button" data-kind="secondary" onClick={() => setConversation(item)}>{item.title}<span>{item.workspaceId}</span></button></li>)}</ul>{conversation ? <><p>Selected: <code>{conversation.title}</code></p><label>Text run<textarea aria-label="Platform prompt" value={draft} onChange={(event) => setDraft(event.currentTarget.value)} /></label><button type="button" disabled={busy || !draft.trim() || !props.model.trim()} onClick={() => void startRun()}>Start text run</button></> : null}{message ? <p className="a008-note">{message}</p> : null}</div> : null}</section>;
}
