import { hostFetch, resolveHostUrl } from "../host/tauri-http.js";
import { resolveHostEndpoints, tryListProjects } from "../host/v2-http.js";
import { tryListSidebarProjects } from "../host/v2-http.js";
import { updateProject as updateProjectRequest } from "../host/v1-http.js";
import { loadInstalledSkills, discoverSkills, installSkill, removeSkill, type InstalledSkill } from "../settings/skills-client.js";
import { uploadSource, uploadSourcePath } from "../upload/upload-source.js";
export type { PromptImageAttachment } from "../session/prompt-attachment.js";
import type { PromptImageAttachment } from "../session/prompt-attachment.js";

export interface PlatformProject { readonly projectId: string; readonly name: string; readonly rootFolder?: string; readonly pinned?: boolean; }
export interface PlatformMessage { readonly role: "user" | "assistant"; readonly content: unknown; readonly runId?: string; }
export interface PlatformConversation { readonly id: string; readonly projectId: string; readonly title: string; readonly workspaceId: string; readonly revision: number; readonly messages: readonly PlatformMessage[]; }
export interface PlatformRun { readonly id: string; readonly commandId: string; readonly status: string; readonly revision: number; readonly error?: { readonly message?: string }; }
export interface WorkspaceSession { readonly id: string; readonly workspacePath: string; readonly branchName?: string; readonly disposition: "active" | "kept" | "discarded"; readonly status: { readonly modifiedFiles: number; readonly commitsAhead: number; readonly clean: boolean }; }
export interface ProjectChatRow { readonly conversationId: string; readonly title: string; readonly updatedAt: string; readonly current: boolean; }
export interface SidebarProject extends PlatformProject { readonly conversations: readonly ProjectChatRow[]; }
export interface ExistingProjectRegistration { readonly projectName: string; readonly rootFolder: string; readonly memory: { readonly useGlobalA008Memory: boolean }; }
export interface ProjectBootstrapConfig { readonly projectName: string; readonly rootFolder: string; readonly repository: { readonly initialize: boolean; readonly name: string }; readonly continuity: { readonly docsFirst: boolean; readonly multiAgent: { readonly enabled: boolean } }; readonly memory: { readonly useGlobalA008Memory: boolean }; }

function isRecord(value: unknown): value is Record<string, unknown> { return value !== null && typeof value === "object" && !Array.isArray(value); }
function messageFromBody(value: unknown): string { if (isRecord(value)) { if (typeof value.message === "string") return value.message; if (isRecord(value.error) && typeof value.error.message === "string") return value.error.message; if (typeof value.error === "string") return value.error; } return "A008 request failed."; }
export function platformPathSegment(value: string, field = "identifier"): string { const trimmed=value.trim(); if (!trimmed || trimmed === "." || trimmed === ".." || /(?:^|[\\/])\.{1,2}(?:[\\/]|$)/u.test(trimmed) || trimmed.length>256) throw new Error(`Invalid ${field}.`); return encodeURIComponent(trimmed); }
async function request<T>(path: string, init: RequestInit = {}, fetchImpl: typeof fetch = hostFetch): Promise<T> { const response=await fetchImpl(resolveHostUrl(path),{cache:"no-store",credentials:"include",...init}); let body:unknown; try { body=await response.json(); } catch { body=undefined; } if(!response.ok) throw new Error(messageFromBody(body)); return body as T; }
export async function loadPlatform(fetchImpl: typeof fetch = hostFetch): Promise<{available:boolean;projects:readonly PlatformProject[];authProfiles:readonly string[]}> { const info=await request<{available:boolean}>("/v3/info",{},fetchImpl); if(!info.available) return {available:false,projects:[],authProfiles:[]}; const listing=await tryListProjects(resolveHostEndpoints("").httpBase,fetchImpl); return {available:true,projects:listing?.projects ?? [],authProfiles:[]}; }
export async function listConversations(projectId:string, fetchImpl:typeof fetch=hostFetch):Promise<readonly PlatformConversation[]> { const result=await request<{conversations:readonly PlatformConversation[]}>(`/v3/projects/${platformPathSegment(projectId,"project id")}/conversations`,{},fetchImpl); if(!Array.isArray(result.conversations)) throw new Error("Host returned an invalid conversation list."); return result.conversations; }
export async function loadConversation(id:string,fetchImpl:typeof fetch=hostFetch):Promise<PlatformConversation> { return (await request<{conversation:PlatformConversation}>(`/v3/conversations/${platformPathSegment(id,"conversation id")}`,{},fetchImpl)).conversation; }
export async function createConversation(projectId:string,title:string,model:string,fetchImpl:typeof fetch=hostFetch):Promise<PlatformConversation> { return (await request<{conversation:PlatformConversation}>(`/v3/projects/${platformPathSegment(projectId,"project id")}/conversations`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({title,...(model?{model}:{})})},fetchImpl)).conversation; }
export async function createRun(conversation:PlatformConversation,text:string,model:string,commandId:string=globalThis.crypto.randomUUID(),fetchImpl:typeof fetch=hostFetch,attachment?:PromptImageAttachment):Promise<{run:PlatformRun;commandId:string}> { const body={commandId,expectedRevision:conversation.revision,model,text,...(attachment?{attachment}:{})}; const result=await request<{run:PlatformRun}>(`/v3/conversations/${platformPathSegment(conversation.id,"conversation id")}/runs`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)},fetchImpl); return {run:result.run,commandId}; }
export async function loadRun(id:string,fetchImpl:typeof fetch=hostFetch):Promise<PlatformRun> { return (await request<{run:PlatformRun}>(`/v3/runs/${platformPathSegment(id,"run id")}`,{},fetchImpl)).run; }
export async function cancelRun(id:string,expectedRevision:number,fetchImpl:typeof fetch=hostFetch):Promise<PlatformRun> { return (await request<{run:PlatformRun}>(`/v3/runs/${platformPathSegment(id,"run id")}/cancel`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({expectedRevision})},fetchImpl)).run; }
export async function loadSkills(fetchImpl:typeof fetch=hostFetch){return loadInstalledSkills(fetchImpl);}
export async function discoverSkillCatalog(fetchImpl:typeof fetch=hostFetch){return discoverSkills(fetchImpl);}
export async function installDiscoveredSkill(path:string,fetchImpl:typeof fetch=hostFetch){return installSkill(path,fetchImpl);}
export async function removeInstalledSkill(id:string,fetchImpl:typeof fetch=hostFetch){return removeSkill(id,fetchImpl);}
export async function uploadImageFile(file:File,fetchImpl:typeof fetch=hostFetch){return uploadSource(file,fetchImpl);}
export async function uploadImagePath(path:string,fetchImpl:typeof fetch=hostFetch){return uploadSourcePath(path,fetchImpl);}
export function storedImageUrl(locator:string):string|undefined { if(!locator.startsWith("source:"))return undefined; const rest=locator.slice(7); const slash=rest.indexOf("/"); if(slash<=0)return undefined; const hash=rest.slice(0,slash),name=rest.slice(slash+1); return /^[a-f0-9]{64}$/u.test(hash)&&name?`/v1/blobs/${hash}/${encodeURIComponent(name)}`:undefined; }
export async function listProjectSidebar(fetchImpl:typeof fetch=hostFetch):Promise<{currentId:string|null;projects:readonly SidebarProject[]}>{return (await tryListSidebarProjects(resolveHostEndpoints("").httpBase,fetchImpl))??{currentId:null,projects:[]};}
export async function saveProject(projectId:string,update:{name?:string;pinned?:boolean},fetchImpl:typeof fetch=hostFetch):Promise<void>{const response=await updateProjectRequest("",{projectId,...update},fetchImpl); void response;}
export async function listRegisteredProjects(fetchImpl:typeof fetch=hostFetch):Promise<readonly PlatformProject[]>{return (await request<{projects:readonly PlatformProject[]}>("/v1/projects",{},fetchImpl)).projects??[];}
export async function browseProjectDirectory(path="",fetchImpl:typeof fetch=hostFetch):Promise<{path:string;entries:readonly string[]}>{return request(`/v1/projects/browse${path?`?path=${encodeURIComponent(path)}`:""}`,{},fetchImpl);}
export async function registerProject(config:ExistingProjectRegistration,fetchImpl:typeof fetch=hostFetch):Promise<void>{await request("/v1/projects/register",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(config)},fetchImpl);}
export async function createProject(config:ProjectBootstrapConfig,fetchImpl:typeof fetch=hostFetch):Promise<void>{const preview=await request<{projectId:string}>("/v1/projects/preview",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(config)},fetchImpl);await request("/v1/projects/bootstrap",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...config,projectId:preview.projectId})},fetchImpl);}
export async function listWorkspaceSessions(projectId:string,fetchImpl:typeof fetch=hostFetch):Promise<readonly WorkspaceSession[]>{return (await request<{sessions:readonly WorkspaceSession[]}>(`/v1/projects/${platformPathSegment(projectId,"project id")}/workspaces`,{},fetchImpl)).sessions;}
export async function createWorkspaceSession(projectId:string,fetchImpl:typeof fetch=hostFetch):Promise<WorkspaceSession>{return await request(`/v1/projects/${platformPathSegment(projectId,"project id")}/workspaces`,{method:"POST",headers:{"content-type":"application/json"},body:"{}"},fetchImpl) as WorkspaceSession;}
export async function updateWorkspaceSession(projectId:string,id:string,action:"keep"|"discard",fetchImpl:typeof fetch=hostFetch):Promise<void>{await request(`/v1/projects/${platformPathSegment(projectId,"project id")}/workspaces/${platformPathSegment(id,"workspace id")}/${action}`,{method:"POST",headers:{"content-type":"application/json"},body:"{}"},fetchImpl);}
export async function getWorkspaceRoot(fetchImpl:typeof fetch=hostFetch):Promise<string>{return (await request<{workspaceRoot:string|null}>("/v1/workspace-settings",{},fetchImpl)).workspaceRoot??"";}
export async function saveWorkspaceRoot(root:string,fetchImpl:typeof fetch=hostFetch):Promise<void>{await request("/v1/workspace-settings",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({workspaceRoot:root})},fetchImpl);}
export function platformMessageText(content: unknown): string { if(typeof content==="string") return content; if(!Array.isArray(content)) return JSON.stringify(content); return content.flatMap((part)=>isRecord(part)&&typeof part.text==="string"?[part.text]:[]).join("\n"); }
export type { InstalledSkill };
